### ISSUE TITLE
Map post images don't load in first open

### ISSUE THREAD

**Issue by TPGamesNL** [DBL-App-development-2023-G7/musicmap#56]
When the map is first opened, osmdroid has to download the map data, and it's loaded in slowly (in a few seconds).
In this time, the music memories will be shown on the map, but their images won't load in. To test, uninstall app or wipe all it's data and (re-install and) open the app, navigate to map.

I don't know why this happens, I tried debugging stuff but couldn't figure it out so gave up for now.
The PostOverlay#setImage is called for all posts, but only for a few of them ImageTarget#onBitmapLoaded is called (few: random, samples: 4/11, 6/11). Even for those where onBitmapLoaded is called, images aren't displayed.

I tried making onBitmapLoaded run on UI thread, cause it interacts with an overlay. I tried fixing the console warning from Bitmap 'getConfig cannot be called on a recycled bitmap'. I tried using a different method to invalidate the view (therefore forcing a redraw)

Here's .patch file for code I used to debug [attempt_to_fix_map_images_not_loading.patch](https://github.com/DBL-App-development-2023-G7/musicmap/files/11132290/attempt_to_fix_map_images_not_loading.patch)

Possible causes:
- bug in Picasso (last release 2020, plenty of commits since). Possible fix would be upgrading Picasso to 3.0.0-SNAPSHOT, with its last release in December 2022, but it may be unstable and it is not API compatible with what we're using rn.
- too much network stuff, so it blocks and Picasso gives an empty image? idk
- postInvalidate and the like doesn't actually trigger a redraw of the overlay. This would not explain why onBitmapLoaded is only called for some

**Comment by TPGamesNL** [comment]
Possibly related:
```
E/PostOverlay: Could not load picture
    java.io.IOException: Failed to decode stream.
        at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:161)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:229)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
I/chatty: uid=10121(com.example.musicmap) identical 11 lines
E/PostOverlay: Could not load picture
    java.io.IOException: Failed to decode stream.
        at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:161)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:229)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
```

**Comment by TPGamesNL** [comment]
Fixed
